import {DEFAULT_CONFIG,PALETTES,escapeHTML as e,linkify,validateBackup,localDate,firstTodoLink,recurringTodos,monthlyDate} from './core.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={recipes:'<path d="M4 19V5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 1 0-4h13M8 7h7M8 11h5"/>',notes:'<path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/>',cars:'<path d="m4 10 2-6h12l2 6M3 10h18v8H3zM5 18v3M19 18v3M6 14h2M16 14h2"/>',todos:'<path d="m3 6 2 2 4-4M12 6h9M3 13l2 2 4-4M12 13h9M12 20h9M4 20h3"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6"/>',web:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]}</svg>`;
const titles={recipes:'Recipes',notes:'Notes',cars:'Cars',todos:'To-Dos',settings:'Settings'};
let theme=localStorage.getItem('red-ridge-theme')==='light'?'light':'dark';
function applyTheme(next=theme){theme=next;document.documentElement.dataset.theme=theme==='light'?'light':'';localStorage.setItem('red-ridge-theme',theme);document.querySelector('meta[name=theme-color]').content=theme==='light'?'#f5f7f6':'#17242d'}
applyTheme();
let tab='recipes',filter='all',query='',selected=null,user=null,records=[],photos=new Map(),cloud=null,cloudPromise=null,loaded=false,photoLoaded=false,toastTimer,pending=0,failedOps=[],lastSyncError='',installPrompt=null;
let trusted=(localStorage.getItem('red-ridge-trusted')??localStorage.getItem('daily-trusted'))==='true';
const dateLabel=s=>{if(!s)return '';const d=new Date(s+'T12:00:00');return isNaN(d)?s:d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})};
const today=localDate();
const get=id=>records.find(x=>x.id===id)||recurringTodos(records).find(x=>x.id===id);const listType=t=>{const saved=records.filter(r=>r.type===t&&!r.deleted);return t==='todo'?saved.concat(recurringTodos(records)):saved};
const readable=r=>r;
const title=r=>r.title;
const byDate=(a,b)=>String(b.date||b.updatedAt).localeCompare(String(a.date||a.updatedAt));
const dayNumber=s=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(s||''));return m?Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]))/86400000:NaN};
const mixColor=(from,to,amount)=>{const a=from.match(/[\da-f]{2}/gi).map(v=>parseInt(v,16)),b=to.match(/[\da-f]{2}/gi).map(v=>parseInt(v,16));return '#'+a.map((v,i)=>Math.round(v+(b[i]-v)*amount).toString(16).padStart(2,'0')).join('')};
const TODO_GRADIENTS={warm:['#E32960','#F9732F','#FEA000'],cool:['#007DC2','#00AB6C','#8AD928']};
function todoPalette(date){const days=dayNumber(date)-dayNumber(localDate());if(Number.isFinite(days)&&days<=0)return 'urgent';return !Number.isFinite(days)||days<=60?'warm':'cool'}
function gradientPosition(index,total){if(total<=1)return 50;if(total<=11)return 50+(index-(total-1)/2)*10;if(total<=101)return index*100/(total-1);return index%101}
function gradientColor(colors,percent){return percent<=50?mixColor(colors[0],colors[1],percent/50):mixColor(colors[1],colors[2],(percent-50)/50)}
function todoColor(date,index=0,total=1){const palette=todoPalette(date);return palette==='urgent'?'#E71C44':gradientColor(TODO_GRADIENTS[palette],gradientPosition(index,total))}
function todoColorSlots(items){const groups={warm:[],cool:[]},slots=new Map();for(const item of items){const palette=todoPalette(item.date);if(palette!=='urgent')groups[palette].push(item)}for(const palette of ['warm','cool'])groups[palette].forEach((item,index)=>slots.set(item.id,{index,total:groups[palette].length}));return slots}
function todoRowColors(date,index=0,total=1){const base=todoColor(date,index,total);return {top:mixColor(base,'#ffffff',.0225),bottom:mixColor(base,'#000000',.0225)}}
function shortTodoDate(date){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(date||''));return m?`${m[2]}/${m[3]}/${m[1].slice(2)}`:''}
function parseTodoDate(value){const m=/^(\d{1,2})\/(\d{1,2})\/(\d{2})$/.exec(String(value||'').trim());if(!m)throw Error('Enter the due date as MM/DD/YY.');const month=Number(m[1]),day=Number(m[2]),year=2000+Number(m[3]),d=new Date(year,month-1,day,12);if(d.getFullYear()!==year||d.getMonth()!==month-1||d.getDate()!==day)throw Error('Enter a valid due date in the 21st century.');return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function formatTodoDateInput(value){const digits=String(value||'').replace(/\D/g,'').slice(0,6);return digits.length<=2?digits:digits.length<=4?`${digits.slice(0,2)}/${digits.slice(2)}`:`${digits.slice(0,2)}/${digits.slice(2,4)}/${digits.slice(4)}`}
const todayTodoCount=()=>listType('todo').filter(t=>!t.done&&t.date===localDate()).length;
function updateTodoBadge(){const button=$('[data-tab="todos"]'),badge=button?.querySelector('.nav-badge');if(!badge)return;const count=todayTodoCount();badge.hidden=!count;badge.textContent=count>99?'99+':String(count);button.setAttribute('aria-label',count?`To-Dos, ${count} due today`:'To-Dos')}
function toast(message,action,label='Undo'){clearTimeout(toastTimer);const node=$('#toast');node.replaceChildren();const s=document.createElement('span');s.textContent=message;node.append(s);if(action){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{node.classList.remove('show');Promise.resolve(action()).catch(err=>toast(err.message))};node.append(b)}node.classList.add('show');toastTimer=setTimeout(()=>node.classList.remove('show'),6500)}
function syncStatus(){updateTodoBadge();let s=(failedOps.length?'Some changes were rejected · retry or export in Settings':'')||lastSyncError||(pending?'Saving changes…':!navigator.onLine?(trusted?'Offline · changes will sync when connected':'Offline · this session only'):loaded?'Connected to Firebase':'Loading your journal…');$('#syncStatus').textContent=s;$('#syncStatus').hidden=tab!=='settings';$('#syncFooter').hidden=tab!=='settings'}
function authGate(message){$('#app').hidden=true;$('#gate').hidden=false;if(message)$('#gateStatus').textContent=message}
async function initCloud(){if(cloud)return cloud;if(cloudPromise)return cloudPromise;cloudPromise=(async()=>{try{const {connect}=await import('./cloud.js');const config=DEFAULT_CONFIG;cloud=await connect(config,trusted,{auth(u){user=u;if(!u){records=[];photos.clear();authGate();return}$('#gate').hidden=true;$('#app').hidden=false;loaded=false;photoLoaded=false;render();},snapshot(name,data,metadata){lastSyncError='';if(name==='records'){records=data;applyOps(failedOps);loaded=true;if(metadata.hasPendingWrites)lastSyncError=navigator.onLine?'Changes queued · waiting for Firebase':'Offline · changes queued';else if(metadata.fromCache)lastSyncError=navigator.onLine?'Showing saved copy · connecting…':'Offline · saved copy'}else{photos=new Map(data.map(p=>[p.id,p]));applyOps(failedOps);photoLoaded=true}renderList();renderDetail();syncStatus()},error(message){lastSyncError=message;$('#gateStatus').textContent=message;syncStatus();if(user)toast(message)}});return cloud}catch(err){cloudPromise=null;$('#gateStatus').textContent='Could not connect to Red Ridge. Check your connection and try again.';throw err}})();return cloudPromise}
async function signIn(){$('#signIn').disabled=true;try{const c=await initCloud();await c.signIn()}catch(err){$('#gateStatus').textContent=err.code==='auth/unauthorized-domain'?'Add snowsences.github.io to Firebase Authentication → Authorized domains.':`Sign-in did not finish. ${err.code||'Check your connection and try again.'}`}finally{$('#signIn').disabled=false}}
$('#signIn').onclick=signIn;
async function persist(ops){if(!user)throw Error('Sign in to save.');const before=structuredClone(records),oldPhotos=new Map(photos);pending++;lastSyncError='';applyOps(ops);renderList();renderDetail();syncStatus();let promise;try{promise=cloud.write(ops)}catch(err){pending--;records=before;photos=oldPhotos;throw err}promise.then(()=>{pending--;syncStatus()}).catch(err=>{pending--;failedOps.push(...ops);applyOps(ops);renderList();renderDetail();lastSyncError='Changes could not sync. '+(err.code||err.message);toast('Save rejected. Open Settings to check the connection.');syncStatus()});}
function applyOps(ops){for(const op of ops){if(op.collection==='photos'){if(op.remove)photos.delete(op.id);else photos.set(op.id,op.value)}else{const idx=records.findIndex(r=>r.id===op.id);if(op.remove){if(idx>=0)records.splice(idx,1)}else if(idx>=0)records[idx]=op.value;else records.push(op.value)}}}
const save=r=>persist([{id:r.id,value:{...r,updatedAt:new Date().toISOString()}}]);
function nav(){$('#nav').innerHTML=Object.keys(titles).map(t=>`<button class="nav-tab ${t===tab?'active':''}" data-tab="${t}" ${t===tab?'aria-current="page"':''} style="--tab:${({recipes:'#ff9277',notes:'#c4a0eb',cars:'#85b9f2',todos:'#85c8d8',settings:'#ffd064'})[t]}">${icon(t)}<span>${titles[t]}</span>${t==='todos'?'<span class="nav-badge" hidden aria-hidden="true"></span>':''}</button>`).join('');updateTodoBadge();$$('#nav [data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;filter='all';query='';selected=null;render()})}
function render(){nav();document.documentElement.style.setProperty('--tab',({recipes:'#ff9277',notes:'#c4a0eb',cars:'#85b9f2',todos:'#85c8d8',settings:'#ffd064'})[tab]);$('#add').hidden=tab==='settings';$('#add').setAttribute('aria-label','Add '+({recipes:'recipe entry',notes:'note',cars:'car',todos:'to-do'})[tab]);$('main').classList.toggle('todo-main',tab==='todos');$('main').dataset.tab=tab;$('#workspace').hidden=tab==='settings';$('#settings').hidden=tab!=='settings';$('#tools').hidden=tab==='settings'||tab==='todos'||tab==='cars';$('#workspace').classList.toggle('single',tab==='todos');if(tab==='settings')renderSettings();else{renderTools();renderList()}renderDetail();syncStatus()}
function renderTools(){let chips=[];if(tab==='notes')chips=[['all','All notes'],['pinned','Pinned']];$('#tools').innerHTML=(tab==='todos'||tab==='cars')?'':`<input class="search" type="search" placeholder="Search ${titles[tab].toLowerCase()}" aria-label="Search ${titles[tab]}" value="${e(query)}">${chips.length?`<div class="chips">${chips.map(([v,l])=>`<button class="chip ${filter===v?'active':''}" data-filter="${v}" aria-pressed="${filter===v}">${l}</button>`).join('')}</div>`:''}`;const search=$('.search');if(search)search.oninput=ev=>{query=ev.target.value;renderList()};$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderTools();renderList()})}
function renderList(){if(tab==='settings'||$('#app').hidden)return;if(!loaded){$('#list').innerHTML='<p class="loading">Loading your journal…</p>';return}if(tab==='todos'){renderTodos();return}let rows=listType(({recipes:'recipe',notes:'note',cars:'car'})[tab]);if(tab==='notes')rows=rows.filter(r=>!r.encrypted&&(filter==='all'||(filter==='pinned'&&r.pinned))).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||byDate(a,b));else if(tab==='cars')rows.sort((a,b)=>Number(a.status==='past')-Number(b.status==='past')||byDate(a,b));else rows.sort(byDate);if(query){const q=query.toLowerCase();rows=rows.filter(r=>tab==='notes'?[r.title,plainRichText(r.body,r.richText)].join('\n').toLowerCase().includes(q):JSON.stringify(r).toLowerCase().includes(q))}
if(!rows.length){$('#list').innerHTML=`<div class="empty"><h2>${query?'No matches':({recipes:'What did you cook?',notes:'Make a little space.',cars:'Your garage starts here.'})[tab]}</h2><p>${query?'Try a different search.':({recipes:'Keep the ingredients, the good bits, and what you’d change next time.',notes:'Keep something useful.',cars:'Add a current car or a car you used to own.'})[tab]}</p>${query?'':'<button class="primary" id="emptyAdd">Add your first entry</button>'}</div>`;$('#emptyAdd')?.addEventListener('click',()=>openEditor());return}
$('#list').innerHTML=rows.map((r,i)=>{const divider=tab==='cars'&&r.status==='past'&&(i===0||rows[i-1].status!=='past')?'<h2 class="section-label">Previously owned</h2>':'';const d=r.date?new Date(r.date+'T12:00:00'):null;let meta=tab==='recipes'?dateLabel(r.date):tab==='notes'?(r.category||'General'):[r.year,r.make,r.model].filter(Boolean).join(' ');const thumb=r.photos?.map(photoSource).find(Boolean);if(tab==='cars'){const cover=carCover(r);return `${divider}<button class="car-card ${selected===r.id?'selected':''}" data-open="${e(r.id)}"><span class="car-card-photo">${cover&&photoSource(cover)?`<img src="${e(photoSource(cover))}" alt="${e(title(r))}" loading="lazy">`:`<span class="car-photo-placeholder">${icon('cars')}<span>Add a cover photo</span></span>`}${r.photos?.length?`<span class="photo-count">${r.photos.length} photo${r.photos.length===1?'':'s'}</span>`:''}</span><span class="car-card-copy"><strong>${e(title(r))}</strong><span>${e(meta)}</span>${r.owner?`<span class="small">${e(r.owner)}</span>`:''}</span></button>`}return `${divider}<button class="band ${selected===r.id?'selected':''}" data-open="${e(r.id)}" style="--band:${PALETTES[tab][Math.min(i,PALETTES[tab].length-1)]}">${tab==='recipes'&&d?`<span class="date-square"><b>${d.getDate()}</b><span>${d.toLocaleDateString(undefined,{month:'short'})}</span></span>`:''}<span class="copy"><strong>${r.pinned?'⌁ ':''}${e(title(r))}</strong><span class="meta">${e(meta)}</span></span>${thumb?`<img class="thumb" src="${e(thumb)}" alt="">`:''}</button>`}).join('');$$('[data-open]').forEach(b=>b.onclick=()=>{selected=b.dataset.open;renderList();renderDetail();if(window.matchMedia('(max-width:680px)').matches)window.scrollTo(0,0)})}
function photoMarkup(items=[]){return items.length?`<div class="photos">${items.map((item,index)=>{const url=photoSource(item);return url?`<button class="photo-open" data-photo-index="${index}" style="padding:0;background:none" aria-label="View photo"><img src="${e(url)}" alt="Journal photo"></button>`:'<p class="small">Photo is not available offline yet.</p>'}).join('')}</div>`:''}
const RICH_TAGS=new Set(['A','B','BLOCKQUOTE','BR','DIV','LI','OL','P','STRONG','UL']);
function sanitizeRichHTML(value){const template=document.createElement('template');template.innerHTML=String(value||'');const clean=parent=>{for(const child of [...parent.childNodes]){if(child.nodeType===Node.COMMENT_NODE){child.remove();continue}if(child.nodeType!==Node.ELEMENT_NODE)continue;if(!RICH_TAGS.has(child.tagName)){clean(child);child.replaceWith(...child.childNodes);continue}const href=child.tagName==='A'?child.getAttribute('href'):'';for(const attribute of [...child.attributes])child.removeAttribute(attribute.name);if(child.tagName==='A')try{const url=new URL(href);if(!['http:','https:'].includes(url.protocol))throw Error();child.href=url.href;child.target='_blank';child.rel='noopener noreferrer'}catch{child.removeAttribute('href')}clean(child)}};clean(template.content);return template.innerHTML}
function linkifyRichHTML(value){const template=document.createElement('template');template.innerHTML=sanitizeRichHTML(value);const visit=parent=>{for(const child of [...parent.childNodes]){if(child.nodeType===Node.TEXT_NODE&&parent.tagName!=='A'&&/https?:\/\//.test(child.data)){const span=document.createElement('span');span.innerHTML=linkify(child.data);child.replaceWith(...span.childNodes)}else if(child.nodeType===Node.ELEMENT_NODE)visit(child)}};visit(template.content);return template.innerHTML}
function plainRichText(value,formatted=false){if(!formatted)return String(value||'');const node=document.createElement('div');node.innerHTML=sanitizeRichHTML(value);return node.textContent||''}
function reading(label,text,formatted=false){return text?`<h3>${label}</h3><div class="reading ${formatted?'rich-reading':''}">${formatted?linkifyRichHTML(text):linkify(text)}</div>`:''}
function renderDetail(){
 const detail=$('#detail'),workspace=$('#workspace');
 const r=!['settings','todos'].includes(tab)?get(selected):null;
 const hasDetail=!!r&&!r.deleted&&!(r.type==='note'&&r.encrypted);
 workspace.classList.toggle('show-detail',hasDetail);
 workspace.classList.toggle('browsing',!hasDetail);
 $('main').classList.toggle('recipe-detail',hasDetail&&tab==='recipes');
 detail.classList.toggle('car-detail',hasDetail&&r.type==='car');
 detail.classList.remove('blank');
 detail.hidden=!hasDetail;
 if(!hasDetail){detail.replaceChildren();return}
 let body='';if(r.type==='recipe'){body=`<p class="sub">${e(dateLabel(r.date))}</p>${photoMarkup(r.photos)}${reading('Ingredients',r.ingredients,r.richText)}${reading('Method',r.method)}${reading('Notes',r.body,r.richText)}`}else if(r.type==='note'){body=`<p class="sub">${e(r.category||'General')}</p><div class="reading ${r.richText?'rich-reading':''}">${r.richText?linkifyRichHTML(r.body):linkify(r.body)}</div>`}else if(r.type==='car'){const logs=listType('maintenance').filter(l=>l.carId===r.id).sort(byDate),reminders=listType('reminder').filter(l=>l.carId===r.id&&!l.done).sort((a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999')));body=`<p class="sub">${e([r.year,r.make,r.model].filter(Boolean).join(' '))}${r.owner?' · '+e(r.owner):''}</p><p class="small car-ownership">${e(carOwnership(r))}</p>${carGallery(r)}${reading('Details',r.body,r.richText)}${r.odometer?`<p>Odometer · ${Number(r.odometer).toLocaleString()} ${e(r.unit||'mi')}</p>`:''}${r.vin?`<p>VIN · ${e(r.vin)}</p>`:''}<h3>Upcoming maintenance</h3>${reminders.length?reminders.map(l=>`<div class="reminder"><button data-child="${e(l.id)}"><b>${e(l.title)}</b><small>${e(dateLabel(l.date)||'No date')}${l.mileage?' · '+Number(l.mileage).toLocaleString()+' '+e(r.unit||'mi'):''}${l.date&&l.date<today?' · Overdue':''}</small></button><button class="text-button" data-reminder-done="${e(l.id)}">Mark done</button></div>`).join(''):'<p class="small">No upcoming maintenance.</p>'}<button class="secondary" id="addReminder">Add reminder</button><h3>Maintenance history</h3>${logs.length?logs.map(l=>`<div class="reminder"><button data-child="${e(l.id)}"><b>${e(l.title)}</b><small>${e(dateLabel(l.date))}${l.mileage?' · '+Number(l.mileage).toLocaleString()+' '+e(r.unit||'mi'):''}${l.cost?' · $'+Number(l.cost).toFixed(2):''}</small></button></div>`).join(''):'<p class="small">No maintenance logged yet.</p>'}<button class="secondary" id="addMaintenance">Log maintenance</button>`}
$('#detail').innerHTML=`${r.type==='car'?carHero(r):''}<div class="${r.type==='car'?'car-content':'entry-content'}"><button class="text-button mobile-back" id="back">‹ Back</button><div class="detail-head"><h2>${e(title(r))}</h2></div>${body}<div class="detail-actions"><button class="secondary" id="editEntry">Edit</button>${r.type==='note'?`<button class="ghost" id="pinNote">${r.pinned?'Unpin':'Pin note'}</button>`:''}<button class="danger" id="deleteEntry">Delete</button></div></div>`;
$('#addCarPhotos')?.addEventListener('click',()=>{openEditor(r);$('#photoInput')?.click()});$('#back').onclick=()=>{selected=null;renderList();renderDetail()};$('#editEntry')?.addEventListener('click',()=>openEditor(r));$('#deleteEntry').onclick=()=>removeRecord(r);$('#pinNote')?.addEventListener('click',()=>save({...r,pinned:!r.pinned}));$('#addReminder')?.addEventListener('click',()=>openEditor(null,'reminder',r.id));$('#addMaintenance')?.addEventListener('click',()=>openEditor(null,'maintenance',r.id));$$('[data-child]').forEach(b=>b.onclick=()=>openEditor(get(b.dataset.child)));$$('[data-reminder-done]').forEach(b=>b.onclick=()=>save({...get(b.dataset.reminderDone),done:true}));$$('[data-photo-index]').forEach(b=>b.onclick=()=>showPhoto(r.id,Number(b.dataset.photoIndex)));}
function nextScheduleDate(schedule,asOf=localDate()){for(let i=0;i<1200;i++){const date=monthlyDate(schedule.startDate,i*schedule.intervalMonths);if(!date||date>=asOf)return date||''}return ''}
async function cancelSchedule(schedule){if(!schedule||schedule.cancelledOn)return;if(!await ask('Cancel reminder?',`Future “${schedule.title}” To-Dos will stop. To-Dos that have already appeared will remain.`,'Cancel reminder',true))return;await save({...schedule,cancelledOn:localDate()});if(tab==='settings')renderSettings();else renderTodos();toast('Recurring reminder canceled')}
function renderTodos(){
 updateTodoBadge();
 const ordered=done=>listType('todo').filter(t=>!!t.done===done).sort((a,b)=>String(a.date||'9999-12-31').localeCompare(String(b.date||'9999-12-31'))||(a.order||0)-(b.order||0));
 const active=ordered(false),done=ordered(true);
 const slots=todoColorSlots(active);
 const row=t=>{const link=firstTodoLink(t.title),slot=slots.get(t.id),colors=todoRowColors(t.date,slot?.index,slot?.total);return `<li class="task-wrap ${t.done?'done':''}" data-id="${e(t.id)}"><div class="underlay complete"><span>✓ ${t.done?'Restore':'Complete'}</span></div><div class="underlay delete"><span>Delete ×</span></div><div class="task-row" tabindex="0" role="button" aria-label="Edit ${e(t.title)}" style="--band-top:${colors.top};--band-bottom:${colors.bottom}"><div class="task-label">${t.date?`<small>${e(dateLabel(t.date))}${!t.done&&t.date<localDate()?' · Overdue':''}</small>`:''}<span>${linkify(link.text)}</span></div>${link.url?`<a class="todo-web-link" href="${e(link.url)}" target="_blank" rel="noopener noreferrer" aria-label="Open link for ${e(t.title)}">${icon('web')}</a>`:''}</div></li>`};
 $('#list').innerHTML=`<ul class="task-list" aria-label="Active To-Dos">${active.length?active.map(row).join(''):done.length?'':'<li class="empty"><h2>Nothing pressing.</h2><p>Enjoy the blank space.</p></li>'}</ul>${done.length?`<div class="completed-group"><div class="completed-delete-all"><button id="deleteCompleted">Delete all</button></div><ul class="task-list" aria-label="Completed To-Dos">${done.map(row).join('')}</ul></div>`:''}`;
 $('#deleteCompleted')?.addEventListener('click',()=>deleteCompleted(done));bindSwipes()
}
function bindSwipes(){$$('.task-wrap').forEach(wrap=>{
 const row=wrap.querySelector('.task-row'),done=wrap.classList.contains('done'),group=wrap.closest('.completed-group');
 let pointer=null,sx=0,sy=0,dx=0,horizontal=false,moved=false,vertical=false,groupWasOpen=false;
 const threshold=()=>Math.min(160,Math.max(108,wrap.clientWidth*.3));
 const groupRows=()=>[...group.querySelectorAll('.task-row')];
 const settleGroup=open=>{group.classList.remove('swiping-delete-all');group.classList.toggle('delete-open',open);for(const item of groupRows()){item.classList.remove('dragging');item.style.transform=''}};
 const reset=()=>{row.classList.remove('dragging');wrap.classList.remove('swiping-right','swiping-left');row.style.transform=''};
 row.onpointerdown=ev=>{if(ev.target.closest('a')||ev.button!==0)return;pointer=ev.pointerId;sx=ev.clientX;sy=ev.clientY;dx=0;horizontal=moved=vertical=false;groupWasOpen=!!group?.classList.contains('delete-open');row.setPointerCapture?.(pointer)};
 row.onpointermove=ev=>{if(ev.pointerId!==pointer||vertical)return;const x=ev.clientX-sx,y=ev.clientY-sy;if(!horizontal&&Math.abs(y)>8&&Math.abs(y)>Math.abs(x)){vertical=true;moved=true;return}if(!horizontal&&Math.abs(x)>8&&Math.abs(x)>Math.abs(y))horizontal=true;if(!horizontal)return;ev.preventDefault();moved=true;dx=Math.max(-240,Math.min(240,x));if(done&&(groupWasOpen||dx<0)){group.classList.add('swiping-delete-all');const offset=Math.max(-116,Math.min(0,(groupWasOpen?-116:0)+dx));for(const item of groupRows()){item.classList.add('dragging');item.style.transform=`translateX(${offset}px)`}}else{row.classList.add('dragging');row.style.transform=`translateX(${dx}px)`;wrap.classList.toggle('swiping-right',dx>12);wrap.classList.toggle('swiping-left',dx< -12)}};
 row.onpointerup=ev=>{if(ev.pointerId!==pointer)return;pointer=null;const r=get(wrap.dataset.id);if(done&&groupWasOpen){settleGroup(!(dx>30||!moved));return}if(done&&dx<0){settleGroup(-dx>=60);return}if(done&&dx>=threshold()){row.classList.remove('dragging');row.classList.add('completing');navigator.vibrate?.(12);setTimeout(()=>{save({...r,done:false});toast('To-Do restored',()=>save(r))},180);return}if(!done&&Math.abs(dx)>=threshold()){row.classList.remove('dragging');row.classList.add(dx>0?'completing':'deleting');navigator.vibrate?.(12);const right=dx>0;setTimeout(()=>{if(right){save({...r,done:true});toast('Marked complete',()=>save(r))}else removeTodo(r)},180);return}reset();if(!moved)openEditor(r)};
 row.onpointercancel=()=>{pointer=null;if(done&&groupWasOpen)settleGroup(true);else if(done&&dx<0)settleGroup(false);else reset()};
 row.onkeydown=ev=>{if(ev.target.closest('a'))return;if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openEditor(get(wrap.dataset.id))}}
})}
function removeTodo(r){save({...r,deleted:true});toast('To-Do deleted',()=>save(r))}
async function deleteCompleted(items){if(!items.length||!await ask('Delete all completed To-Dos?',`Permanently remove ${items.length} completed item${items.length===1?'':'s'}?`,'Delete all',true))return;const stamp=new Date().toISOString();await persist(items.map(item=>({id:item.id,value:{...item,deleted:true,updatedAt:stamp}})));toast('Completed To-Dos deleted',()=>persist(items.map(item=>({id:item.id,value:item}))))}
async function ask(title,message,action='Continue',danger=false){const d=$('#confirm');d.innerHTML=`<div class="modal-head"><h2>${e(title)}</h2></div><div class="form-body"><p>${e(message)}</p></div><div class="form-actions"><button id="no" class="ghost">Cancel</button><button id="yes" class="${danger?'danger':'primary'}">${e(action)}</button></div>`;d.showModal();return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;d.close();resolve(v)};$('#no').onclick=()=>finish(false);$('#yes').onclick=()=>finish(true);d.oncancel=ev=>{ev.preventDefault();finish(false)}})}
async function removeRecord(r){if(!await ask('Delete '+(r.type==='car'?'this car':r.type==='note'?'this note':'this entry')+'?',r.type==='car'?'This also removes its maintenance logs and reminders.':'You can undo this immediately after deleting.','Delete',true))return;const related=records.filter(x=>x.id===r.id||(r.type==='car'&&x.carId===r.id));await persist(related.map(x=>({id:x.id,value:{...x,deleted:true}})));selected=null;renderList();renderDetail();toast('Deleted',()=>persist(related.map(x=>({id:x.id,value:x}))))}
function field(name,label,value='',type='text',required=false){return `<label>${label}<input name="${name}" type="${type}" value="${e(value)}" ${required?'required':''} ${type==='number'?'min="0" step="any"':''} ${name==='title'?'maxlength="500"':type==='text'?'maxlength="1000"':''}></label>`}
function area(name,label,value='',max=20000){return `<label>${label}<textarea name="${name}" maxlength="${max}">${e(value)}</textarea></label>`}
function richArea(name,label,value='',formatted=false,max=20000){const html=formatted?sanitizeRichHTML(value):e(value).replace(/\r?\n/g,'<br>');return `<div class="rich-field"><label for="rich-${name}">${label}</label><div id="rich-${name}" class="rich-editor" contenteditable="true" role="textbox" aria-multiline="true" data-name="${name}" data-max="${max}">${html}</div><textarea name="${name}" hidden>${e(sanitizeRichHTML(html))}</textarea></div>`}
function bindRichEditors(form,markDirty){const placeCaret=node=>{const selection=getSelection(),range=document.createRange();range.selectNodeContents(node);range.collapse(false);selection.removeAllRanges();selection.addRange(range)};const selectionNode=editor=>{const selection=getSelection();if(!selection?.rangeCount)return null;let node=selection.anchorNode;if(node?.nodeType===Node.TEXT_NODE)node=node.parentElement;return node&&editor.contains(node)?node:null};for(const editor of $$('.rich-editor')){if(!form.contains(editor))continue;const field=form.elements[editor.dataset.name],max=Number(editor.dataset.max)||20000;let last=field.value;const sync=()=>{const html=sanitizeRichHTML(editor.innerHTML);if(plainRichText(html,true).length>max){editor.innerHTML=last;placeCaret(editor);return}last=html;field.value=html;markDirty()};editor.addEventListener('input',sync);editor.addEventListener('paste',event=>{event.preventDefault();const html=event.clipboardData?.getData('text/html'),text=event.clipboardData?.getData('text/plain')||'',safe=html?sanitizeRichHTML(html):e(text).replace(/\r?\n/g,'<br>');document.execCommand('insertHTML',false,safe);sync()});editor.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='b'){event.preventDefault();document.execCommand('bold',false,null);sync();return}const node=selectionNode(editor),item=node?.closest?.('li');if(event.key==='Tab'&&item){event.preventDefault();document.execCommand(event.shiftKey?'outdent':'indent',false,null);sync();return}if(event.key===' '&&!event.metaKey&&!event.ctrlKey&&!event.altKey){let block=node;while(block&&block!==editor&&!['DIV','P','LI'].includes(block.tagName))block=block.parentElement;const marker=(block||editor).textContent.trim();if(['1.','•','-','*'].includes(marker)){event.preventDefault();document.execCommand(marker==='1.'?'insertOrderedList':'insertUnorderedList',false,null);let current=selectionNode(editor)?.closest?.('li');if(current&&current.textContent.trim()===marker){current.textContent='';placeCaret(current)}sync()}}});editor.addEventListener('blur',sync)}}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select></label>`}
function photoKey(photo){return typeof photo==='string'?photo:photo?.id}
function photoSource(photo){if(typeof photo==='string')return photos.get(photo)?.data||'';return photo?.url||''}
function getCloudinaryConfig(){try{const config=JSON.parse((localStorage.getItem('red-ridge-cloudinary')||localStorage.getItem('daily-cloudinary'))||'null');if(config&&/^[A-Za-z0-9_-]+$/.test(config.cloudName)&&/^[A-Za-z0-9_-]+$/.test(config.uploadPreset))return config}catch{}return null}
function dataURLBlob(data){const [head,body]=data.split(',');const type=head.match(/^data:([^;]+);base64$/)?.[1];if(!type)throw Error('Could not prepare this photo.');const binary=atob(body),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type})}
const MAX_IMAGE_BYTES=8*1024*1024;
const blobDataURL=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not prepare this photo.'));reader.readAsDataURL(blob)});
const canvasJPEG=canvas=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('Could not resize this photo.')),'image/jpeg',.9));
async function uploadCloudinary(photo,type){if(!navigator.onLine)throw Error('Connect to the internet to upload photos to Cloudinary. You can save the entry without photos while offline.');const config=getCloudinaryConfig();if(!config)throw Error('Set your Cloudinary cloud name and unsigned upload preset in Settings before adding photos.');const blob=dataURLBlob(photo.data);if(blob.size>MAX_IMAGE_BYTES)throw Error('This photo is still larger than 8 MB.');const form=new FormData();form.append('file',blob,photo.name||'red-ridge-photo.jpg');form.append('upload_preset',config.uploadPreset);form.append('asset_folder',({recipe:'Red Ridge/Recipes',car:'Red Ridge/Cars',maintenance:'Red Ridge/Cars/Maintenance'})[type]||'Red Ridge');const response=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(config.cloudName)}/image/upload`,{method:'POST',body:form});let result={};try{result=await response.json()}catch{}if(!response.ok)throw Error(result?.error?.message||'Cloudinary could not upload this photo.');if(typeof result.secure_url!=='string'||!result.secure_url.startsWith(`https://res.cloudinary.com/${config.cloudName}/image/upload/`)||typeof result.public_id!=='string')throw Error('Cloudinary returned an unexpected photo address.');return {id:photo.id,url:result.secure_url,publicId:result.public_id,width:Number(result.width)||null,height:Number(result.height)||null,bytes:Number(result.bytes)||null}}
async function compress(file){if(file.size>80*1024*1024)throw Error('Choose photos smaller than 80 MB.');if(!/^image\/(jpeg|png|webp|avif)$/.test(file.type))throw Error('Use JPEG, PNG, WebP, or AVIF photos.');const id=crypto.randomUUID();if(file.size<=MAX_IMAGE_BYTES)return {id,data:await blobDataURL(file),name:file.name||'red-ridge-photo',bytes:file.size};const bitmap=await createImageBitmap(file);let scale=Math.min(1,Math.sqrt((MAX_IMAGE_BYTES*.9)/file.size)),w=Math.max(1,Math.floor(bitmap.width*scale)),h=Math.max(1,Math.floor(bitmap.height*scale)),blob;const canvas=document.createElement('canvas');for(let attempt=0;attempt<12;attempt++){canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(bitmap,0,0,w,h);blob=await canvasJPEG(canvas);if(blob.size<=MAX_IMAGE_BYTES)break;const step=Math.min(.9,Math.sqrt((MAX_IMAGE_BYTES*.9)/blob.size));w=Math.max(1,Math.floor(w*step));h=Math.max(1,Math.floor(h*step))}bitmap.close();if(!blob||blob.size>MAX_IMAGE_BYTES)throw Error('This photo could not be reduced below 8 MB.');return {id,data:await blobDataURL(blob),name:'red-ridge-photo.jpg',bytes:blob.size}}
function openEditor(record=null,kind=null,carId=null){const type=kind||record?.type||({recipes:'recipe',notes:'note',cars:'car',todos:'todo'})[tab];if(!type||record?.encrypted)return;const r=record||{};const d=$('#editor');let attachmentIds=[...(record?.photos||[])],newPhotos=new Map(),removed=false;let fields=type==='todo'?`<label>To-Do<textarea class="todo-title" name="title" maxlength="300" rows="1" required autofocus>${e(r.title||'')}</textarea></label>`:field('title',({recipe:'What did you cook?',note:'Title',car:'Name',maintenance:'What was done?',reminder:'What needs doing?'})[type],r.title||'','text',true);
if(type==='recipe')fields+=field('date','Date',r.date||today,'date',true)+richArea('ingredients','Ingredients',r.ingredients,r.richText)+area('method','Method',r.method)+richArea('body','Notes',r.body,r.richText);
if(type==='note')fields+=field('category','Category',r.category||'General')+richArea('body','Note',r.body,r.richText)+`<label class="check"><input name="pinned" type="checkbox" ${record?.pinned?'checked':''}>Pin this note</label>`;
if(type==='car')fields+=`<div class="two">${field('year','Year',r.year,'number')}${field('make','Make',r.make)}</div>${field('model','Model / trim',r.model)}${field('owner','Owner',r.owner)}${select('status','Ownership',[['current','Currently owned'],['past','Previously owned']],r.status||'current')}<div class="two">${field('ownedFrom','Owned from',r.ownedFrom,'date')}${field('ownedTo','Owned until',r.ownedTo,'date')}</div><div class="two">${field('odometer','Odometer',r.odometer,'number')}${select('unit','Units',[['mi','Miles'],['km','Kilometers']],r.unit||'mi')}</div>${field('vin','VIN',r.vin)}${richArea('body','Details & memories',r.body,r.richText)}`;
if(type==='todo')fields+=`${!record?'<label class="check recurring-check"><input name="recurring" type="checkbox">Set recurring</label>':''}<label><span id="todoDateLabel">Due date</span><input class="todo-date" name="date" type="text" value="${e(shortTodoDate(r.date))}" inputmode="numeric" autocomplete="off" placeholder="MM/DD/YY" maxlength="8" required></label>${!record?`<div id="recurringFields" hidden>${select('intervalMonths','Frequency',Array.from({length:12},(_,i)=>[String(i+1),`Every ${i+1} month${i?'s':''}`]),'6')}<p class="small">Each To-Do appears seven days before its due date. The schedule stays anchored to the start date.</p></div>`:''}`;
if(type==='maintenance'||type==='reminder')fields+=field('date',type==='maintenance'?'Date':'Due date (optional)',r.date||(type==='maintenance'?today:''),'date',type==='maintenance')+field('mileage',type==='maintenance'?'Odometer':'Due at odometer (optional)',r.mileage,'number')+(type==='maintenance'?field('cost','Cost (USD)',r.cost,'number')+field('provider','Shop / provider',r.provider):'')+area('body','Notes',r.body);
const maxPhotos=type==='car'?100:12;
if(['recipe','car','maintenance'].includes(type))fields+=`<label>Photos<input id="photoInput" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple></label><p class="small">Photos up to 8 MB keep their original dimensions. Larger photos are scaled down until they fit. Images are never enlarged. Select multiple photos at once. Up to ${maxPhotos} per entry.</p><div id="attachments" class="photos"></div>`;
d.innerHTML=`<form><div class="modal-head"><h2>${record?'Edit':'New'} ${({recipe:'recipe entry',note:'note',car:'car',todo:'To-Do',maintenance:'maintenance log',reminder:'reminder'})[type]}</h2><button class="text-button" type="button" data-close aria-label="Close editor">×</button></div><div class="form-body">${fields}<p class="form-error" role="alert"></p></div><div class="form-actions">${record&&['maintenance','reminder','todo'].includes(type)?'<button type="button" class="danger" id="deleteChild">Delete</button>':''}${record?.type==='todo'&&record.scheduleId?'<button type="button" class="secondary" id="cancelTodoReminder">Cancel reminder</button>':''}${record?.type==='todo'?`<button type="button" class="secondary" id="toggleTodo">${record.done?'Restore':'Complete'}</button>`:''}<button type="button" class="ghost" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`;
let dirty=false,submitting=false;const form=d.querySelector('form');form.oninput=()=>{dirty=true};bindRichEditors(form,()=>{dirty=true});const close=async()=>{if(submitting)return;if(dirty&&!await ask('Discard changes?','Your unsaved changes will be lost.','Discard',true))return;removed=true;d.close()};$$('[data-close]').forEach(b=>b.onclick=close);d.oncancel=ev=>{ev.preventDefault();close()};d.querySelector('[name=recurring]')?.addEventListener('change',ev=>{$('#recurringFields').hidden=!ev.target.checked;$('#todoDateLabel').textContent=ev.target.checked?'Start date':'Due date';dirty=true});
const drawAttachments=()=>{const a=$('#attachments');if(!a)return;a.innerHTML=attachmentIds.map(item=>{const key=photoKey(item),url=newPhotos.get(key)?.data||photoSource(item);return `<div class="attachment"><img src="${e(url)}" alt="Attached photo"><button type="button" data-remove-photo="${e(key)}" aria-label="Remove photo">×</button></div>`}).join('');$$('[data-remove-photo]').forEach(b=>b.onclick=()=>{attachmentIds=attachmentIds.filter(item=>photoKey(item)!==b.dataset.removePhoto);dirty=true;drawAttachments()})};drawAttachments();
$('#photoInput')?.addEventListener('change',async ev=>{const input=ev.target,files=[...input.files],button=form.querySelector('[type=submit]');button.disabled=true;input.disabled=true;try{if(attachmentIds.length+files.length>maxPhotos)throw Error(`Keep up to ${maxPhotos} photos per entry.`);for(const file of files){const p=await compress(file);if(removed)return;newPhotos.set(p.id,p);attachmentIds.push(p.id)}dirty=true;drawAttachments();form.querySelector('.form-error').textContent=''}catch(err){form.querySelector('.form-error').textContent=err.message}finally{button.disabled=false;input.disabled=false;input.value=''}});
$('#deleteChild')?.addEventListener('click',async()=>{d.close();await removeRecord(record)});$('#toggleTodo')?.addEventListener('click',async()=>{await save({...record,done:!record.done});d.close()});$('#cancelTodoReminder')?.addEventListener('click',async()=>{const schedule=get(record.scheduleId);d.close();await cancelSchedule(schedule)});
form.onsubmit=async ev=>{ev.preventDefault();if(submitting)return;submitting=true;const button=form.querySelector('[type=submit]');button.disabled=true;const error=form.querySelector('.form-error');try{const f=new FormData(form),val=k=>String(f.get(k)||'').trim();if(!val('title'))throw Error('Add a title first.');let next={id:record?.id||crypto.randomUUID(),type,title:val('title'),createdAt:record?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const fieldsByType={recipe:['date','ingredients','method','body'],note:['category','body'],car:['year','make','model','owner','status','ownedFrom','ownedTo','odometer','unit','vin','body'],todo:['date'],maintenance:['date','mileage','cost','provider','body'],reminder:['date','mileage','body']};for(const k of fieldsByType[type])next[k]=val(k);if(type==='car'&&next.ownedFrom&&next.ownedTo&&next.ownedTo<next.ownedFrom)throw Error('Owned until must be after owned from.');if(type==='reminder'&&!next.date&&!next.mileage)throw Error('Add a due date or odometer reading.');if(['maintenance','reminder'].includes(type)){next.carId=record?.carId||carId;next.done=record?.done||false}if(type==='todo'){const date=parseTodoDate(next.date),order=record?.order??listType('todo').reduce((m,x)=>Math.max(m,x.order||0),-1)+1;if(!record&&f.has('recurring')){const intervalMonths=Number(val('intervalMonths'));if(!Number.isInteger(intervalMonths)||intervalMonths<1||intervalMonths>12)throw Error('Choose a frequency from 1 to 12 months.');next={id:'schedule_'+crypto.randomUUID(),type:'todoSchedule',title:next.title,startDate:date,intervalMonths,order,createdAt:next.createdAt,updatedAt:next.updatedAt}}else{next.date=date;next.done=record?.done||false;next.order=order;if(record?.scheduleId){next.scheduleId=record.scheduleId;next.scheduledDate=record.scheduledDate}}}if(['recipe','car','maintenance'].includes(type)){const finalPhotos=[];for(const item of attachmentIds){const key=photoKey(item);if(newPhotos.has(key))finalPhotos.push(await uploadCloudinary(newPhotos.get(key),type));else finalPhotos.push(item)}next.photos=finalPhotos;if(type==='car')next.coverPhotoId=finalPhotos.some(p=>photoKey(p)===record?.coverPhotoId)?record.coverPhotoId:(photoKey(finalPhotos[0])||'');}
if(['recipe','note','car'].includes(type))next.richText=true;if(type==='note')next.pinned=f.has('pinned');
const ops=[{id:next.id,value:next}];await persist(ops);if(!['maintenance','reminder','todo'].includes(type))selected=next.id;dirty=false;removed=true;d.close();renderList();renderDetail();toast(next.type==='todoSchedule'?'Recurring reminder created':navigator.onLine?'Saved · syncing with Firebase':'Saved to offline queue');}catch(err){error.textContent=err.message}finally{submitting=false;button.disabled=false}};d.showModal();if(type==='todo'){const input=form.elements.title,dateInput=form.elements.date,resize=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,240)+'px';input.style.overflowY=input.scrollHeight>240?'auto':'hidden'};input.addEventListener('input',resize);dateInput.addEventListener('input',()=>{const formatted=formatTodoDateInput(dateInput.value);if(dateInput.value!==formatted)dateInput.value=formatted});resize();requestAnimationFrame(()=>input.focus())}}
$('#editor').addEventListener('close',()=>{$('#editor').innerHTML='';$('#editor').oncancel=null});
$('#add').onclick=()=>openEditor();$('#home').onclick=()=>{tab='recipes';selected=null;filter='all';query='';render()};
function carCover(r){return r.photos?.find(p=>photoKey(p)===r.coverPhotoId)||r.photos?.[0]}
function carOwnership(r){if(r.status==='past')return r.ownedFrom?`Owned ${dateLabel(r.ownedFrom)}${r.ownedTo?' – '+dateLabel(r.ownedTo):''}`:r.ownedTo?`Owned until ${dateLabel(r.ownedTo)}`:'Previously owned';return r.ownedFrom?`Owned since ${dateLabel(r.ownedFrom)}`:'Currently owned'}
function carHero(r){const cover=carCover(r),url=photoSource(cover);return url?`<button class="car-hero" data-photo-index="${r.photos.indexOf(cover)}" aria-label="Open photos of ${e(title(r))}"><img src="${e(url)}" alt="${e(title(r))}"><span class="photo-count">View ${r.photos.length===1?'photo':r.photos.length+' photos'}</span></button>`:''}
function carGallery(r){return `<div class="car-gallery">${(r.photos||[]).map((photo,index)=>photoSource(photo)?`<button class="car-gallery-thumb ${photo===carCover(r)?'is-cover':''}" data-photo-index="${index}" aria-label="View photo ${index+1}${photo===carCover(r)?', cover photo':''}"><img src="${e(photoSource(photo))}" alt="" loading="lazy"></button>`:'').join('')}</div><button class="ghost" id="addCarPhotos">Add photos</button>`}
let photoViewerState=null;
function showPhoto(recordId,index=0){
 const r=get(recordId);if(!r?.photos?.length)return;
 let d=$('#photoViewer');
 if(!d){d=document.createElement('dialog');d.id='photoViewer';d.className='photo-viewer';d.setAttribute('aria-label','Photo gallery');document.body.append(d);
  d.addEventListener('close',()=>{photoViewerState=null;d.replaceChildren()});
  d.addEventListener('keydown',ev=>{if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();stepPhoto(ev.key==='ArrowLeft'?-1:1)}});
 }
 photoViewerState={recordId,index};renderPhotoViewer();d.showModal();
}
function stepPhoto(direction){if(!photoViewerState)return;const r=get(photoViewerState.recordId);if(!r?.photos?.length)return;photoViewerState.index=(photoViewerState.index+direction+r.photos.length)%r.photos.length;renderPhotoViewer(direction<0?'previousPhoto':'nextPhoto')}
function renderPhotoViewer(focusId){
 const state=photoViewerState,d=$('#photoViewer');if(!state||!d)return;
 const r=get(state.recordId);if(!r?.photos?.length||r.deleted){if(d.open)d.close();return}
 state.index=Math.min(state.index,r.photos.length-1);const photo=r.photos[state.index],url=photoSource(photo),cover=photoKey(carCover(r))===photoKey(photo);
 d.innerHTML=`<div class="photo-viewer-toolbar"><div>${r.type==='car'?(cover?'<span class="cover-badge">Cover Photo</span>':'<button class="primary" id="setCoverPhoto">Set as Cover Photo</button>'):`<span>${e(title(r))}</span>`}</div><button class="text-button" id="closePhoto" aria-label="Close photo gallery">×</button></div><div class="photo-viewer-stage">${url?`<img src="${e(url)}" alt="${e(title(r))}, photo ${state.index+1}">`:'<p>Photo is not available offline yet.</p>'}<button class="photo-arrow previous" id="previousPhoto" aria-label="Previous photo" ${r.photos.length<2?'hidden':''}>&lt;</button><button class="photo-arrow next" id="nextPhoto" aria-label="Next photo" ${r.photos.length<2?'hidden':''}>&gt;</button></div><p class="photo-position" aria-live="polite">${state.index+1} / ${r.photos.length}</p>`;
 $('#closePhoto').onclick=()=>d.close();$('#previousPhoto').onclick=()=>stepPhoto(-1);$('#nextPhoto').onclick=()=>stepPhoto(1);
 $('#setCoverPhoto')?.addEventListener('click',async ev=>{ev.currentTarget.disabled=true;try{const latest=get(state.recordId);if(!latest||latest.deleted||!latest.photos?.some(p=>photoKey(p)===photoKey(photo)))throw Error('This photo is no longer attached to the car.');await save({...latest,coverPhotoId:photoKey(photo)});if(photoViewerState===state&&d.open)renderPhotoViewer('closePhoto');toast('Cover photo updated · syncing')}catch(err){toast(err.message);if(photoViewerState===state&&d.open)renderPhotoViewer('setCoverPhoto')}});
 if(focusId)document.getElementById(focusId)?.focus();
}
function cloudinaryEditor(){const current=getCloudinaryConfig()||{cloudName:'',uploadPreset:''};const d=$('#editor');d.innerHTML=`<form><div class="modal-head"><h2>Cloudinary photos</h2><button class="text-button" type="button" id="closeCloudinary" aria-label="Close">×</button></div><div class="form-body"><p>Red Ridge uploads compressed recipe, car, and maintenance photos to a dedicated unsigned preset.</p>${field('cloudName','Cloud name',current.cloudName,'text',true)}${field('uploadPreset','Unsigned upload preset',current.uploadPreset,'text',true)}<p class="small">The app limits each upload to 8 MB and organizes assets under Red Ridge. In Cloudinary, enforce the same 8 MB limit, allow JPEG, PNG, WebP, and AVIF, generate unique filenames, disallow custom public IDs, and disable overwrite. The cloud name and unsigned preset are visible in any static web app.</p><p class="form-error"></p></div><div class="form-actions"><button class="ghost" type="button" id="clearCloudinary">Clear</button><button class="primary">Save</button></div></form>`;$('#closeCloudinary').onclick=()=>d.close();$('#clearCloudinary').onclick=()=>{localStorage.removeItem('red-ridge-cloudinary');localStorage.removeItem('daily-cloudinary');d.close();renderSettings()};d.querySelector('form').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target),config={cloudName:String(f.get('cloudName')||'').trim(),uploadPreset:String(f.get('uploadPreset')||'').trim()};if(!/^[A-Za-z0-9_-]+$/.test(config.cloudName)||!/^[A-Za-z0-9_-]+$/.test(config.uploadPreset)){d.querySelector('.form-error').textContent='Use only letters, numbers, hyphens, and underscores.';return}localStorage.setItem('red-ridge-cloudinary',JSON.stringify(config));d.close();renderSettings();toast('Cloudinary settings saved')};d.showModal()}
function todoSettingsCard(){const schedules=listType('todoSchedule').filter(schedule=>!schedule.cancelledOn);return `<section class="setting-card" style="--band:#e05c68"><h2>To-Do settings</h2><h3>Reminders</h3>${schedules.length?`<div class="setting-reminders">${schedules.map(schedule=>`<div class="setting-reminder"><div><strong>${e(schedule.title)}</strong><span>Every ${schedule.intervalMonths} month${schedule.intervalMonths===1?'':'s'} · Next ${e(dateLabel(nextScheduleDate(schedule)))}</span></div><button class="ghost" data-cancel-schedule="${e(schedule.id)}">Cancel</button></div>`).join('')}</div>`:'<p class="small">No recurring reminders.</p>'}</section>`}
function renderSettings(){$('#settings').innerHTML=`<div class="setting-grid"><div><section class="setting-card" style="--band:#4c889c"><h2>Account & sync</h2><p>${e(user?.email||'Sign in with your Google account.')}</p><p class="small">${e(lastSyncError||'Red Ridge connects to your red-ridge-d47fa Firebase project.')}</p>${failedOps.length?'<button class="primary" id="retryFailed">Retry rejected changes</button>':''}<button class="ghost" id="signOut">Sign out & clear this device</button></section><section class="setting-card" style="--band:#d96f49"><h2>Appearance</h2><p>Use Red Ridge in its original dark theme or the lighter Estuary palette.</p><button class="secondary" id="themeToggle">${theme==='light'?'Use dark mode':'Use light mode'}</button></section><section class="setting-card" style="--band:#b85f4b"><h2>Cloudinary photos</h2><p>${getCloudinaryConfig()?'Ready to upload photos.':'Add your Cloudinary cloud name and unsigned upload preset.'}</p><p class="small">Red Ridge compresses photos before upload and stores their Cloudinary URLs in Firebase. Standard delivery URLs can be opened by anyone who obtains the link.</p><button class="secondary" id="cloudinary">Cloudinary settings</button></section></div><div>${todoSettingsCard()}<section class="setting-card" style="--band:#d2a64c"><h2>Backup & restore</h2><p>Export your entries and Cloudinary photo references as a JSON file.</p><p class="small">Entry text is readable in the backup. Keep it somewhere private. Import adds missing entries; existing IDs are kept.</p><button class="primary" id="export">Export backup</button><button class="secondary" id="import">Import backup</button><input id="importFile" type="file" accept="application/json,.json" hidden><p id="backupStatus" class="small"></p></section><section class="setting-card" style="--band:#4f8791"><h2>Offline & installation</h2><p>${trusted?'Offline saving is enabled on this trusted device.':'Offline saving is off on this device.'}</p><p class="small">${trusted?'Open Red Ridge online once to cache the app and journal. Text changes queue while offline and sync when you reconnect. New photo uploads require a connection.':'Enable it to keep your journal and queued changes through restarts. Use only on your own device.'}</p><button class="secondary" id="offlineToggle">${trusted?'Turn off offline saving':'Enable offline saving'}</button><button class="ghost" id="install">Install Red Ridge</button><p class="small">Notifications are not enabled. Maintenance reminders live in Cars.</p><p class="small" id="swState"></p></section></div></div>`;
$('#retryFailed')?.addEventListener('click',async()=>{const ops=failedOps;failedOps=[];await persist(ops);renderSettings()});$('#cloudinary').onclick=cloudinaryEditor;$('#themeToggle').onclick=()=>{applyTheme(theme==='light'?'dark':'light');renderSettings()};$$('[data-cancel-schedule]').forEach(button=>button.onclick=()=>cancelSchedule(get(button.dataset.cancelSchedule)));$('#signOut').onclick=async()=>{if(pending||failedOps.length||lastSyncError.includes('queued')){toast('Reconnect and wait for your changes to sync before signing out.');return}if(!await ask('Sign out?','Your offline copy will be removed from this device. Your synced journal stays in Firebase.','Sign out'))return;try{await cloud.signOut();location.reload()}catch(err){toast('Close other Red Ridge tabs, then reload to finish clearing this device. '+(err.code||''))}};
$('#export').onclick=exportBackup;$('#import').onclick=()=>$('#importFile').click();$('#importFile').onchange=importBackup;$('#offlineToggle').onclick=async()=>{if(pending||failedOps.length){toast('Wait for changes to sync first.');return}if(!await ask(trusted?'Turn off offline saving?':'Enable offline saving?',trusted?'Sign out and clear this device first. You can sign in again without offline saving.':'A copy of your journal will remain on this device. Only enable this on a private device.','Continue'))return;try{await cloud.signOut();localStorage.setItem('red-ridge-trusted',String(!trusted));location.reload()}catch{toast('Close other Red Ridge tabs and try again.')}};$('#install').onclick=install;$('#swState').textContent='Service worker: '+('serviceWorker' in navigator?(navigator.serviceWorker.controller?'active':'ready after the first reload'):'not supported by this browser');}
async function exportBackup(){if(!loaded||!photoLoaded){toast('Wait for entries and photos to finish loading.');return}const legacy=new Map(),active=records.filter(r=>!r.deleted).map(record=>{const copy=structuredClone(record);copy.photos=(copy.photos||[]).map(photo=>{if(typeof photo==='string'){const stored=photos.get(photo);if(stored)legacy.set(photo,stored);return photo}if(photo.url?.startsWith('data:image/jpeg;base64,')){legacy.set(photo.id,{id:photo.id,data:photo.url});return photo.id}return photo});return copy});const missing=active.flatMap(r=>r.photos||[]).filter(photo=>typeof photo==='string'&&!legacy.has(photo));if(missing.length){toast('Some legacy photos are not cached. Connect before exporting.');return}const data={app:'red-ridge',version:1,exportedAt:new Date().toISOString(),records:active,photos:[...legacy.values()]};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`red-ridge-backup-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exported')}
async function importBackup(ev){const file=ev.target.files[0];if(!file)return;try{if(file.size>100*1024*1024)throw Error('Choose a backup smaller than 100 MB.');const data=validateBackup(JSON.parse(await file.text()));const existing=new Set(records.map(r=>r.id));const fresh=data.records.filter(r=>!existing.has(r.id));if(!fresh.length){toast('All entries are already in this journal.');return}if(!await ask('Import backup?',`Add ${fresh.length} entries? Existing entries will be kept.`,'Import'))return;const ids=new Set(fresh.flatMap(r=>r.photos||[]));const ops=data.photos.filter(p=>ids.has(p.id)&&!photos.has(p.id)).map(p=>({collection:'photos',id:p.id,value:p})).concat(fresh.map(r=>({id:r.id,value:r})));let batch=[],size=0;for(const op of ops){const n=JSON.stringify(op).length;if(batch.length>=200||size+n>4000000){await persist(batch);batch=[];size=0}batch.push(op);size+=n}if(batch.length)await persist(batch);toast(`Imported ${fresh.length} entries`)}catch(err){toast(err.message)}finally{ev.target.value=''}}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null}else toast('Use your browser menu → Install app or Add to Home Screen.')}
window.addEventListener('beforeinstallprompt',ev=>{ev.preventDefault();installPrompt=ev});window.addEventListener('online',()=>{lastSyncError='';syncStatus()});window.addEventListener('offline',syncStatus);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{$('#gateStatus').textContent='Offline installation is unavailable in this browser. Online use still works.'});
initCloud().catch(()=>{});
window.addEventListener('beforeunload',event=>{if(failedOps.length||(!trusted&&pending)){event.preventDefault();event.returnValue=''}});
